// Fallback static data — used as initial store state when Supabase is not yet configured
// or when the device is offline. Mirrors the seed data in 001_initial_schema.sql.

import type { Energy } from '@/constants/energies';
import type { TarotCard } from '@/constants/tarotData';
import type { MeditationItem, MoodOption, GoalOption } from '@/constants/meditations';
import { MINOR_ARCANA } from '@/constants/minorArcana';

export const FALLBACK_ENERGIES: Energy[] = [
  { id: 1,  name: 'Маг',               arcana: 'The Magician',      planet: 'Меркурій', planetEn: 'Mercury', keywords: ['воля','майстерність','ініціатива'], keywordsEn: ['willpower','mastery','initiative'], positive: 'Лідерство, впевненість, здатність досягати цілей', positiveEn: 'Leadership, confidence, ability to achieve goals', negative: 'Маніпуляції, егоїзм, хитрість', negativeEn: 'Manipulation, egoism, cunning', advice: 'Розвивайте свої таланти та використовуйте силу волі для досягнення цілей', adviceEn: 'Develop your talents and use willpower to achieve your goals' },
  { id: 2,  name: 'Жриця',             arcana: 'The High Priestess', planet: 'Місяць', planetEn: 'Moon', keywords: ['інтуїція','мудрість','таємниця'], keywordsEn: ['intuition','wisdom','mystery'], positive: 'Глибока інтуїція, мудрість, чутливість', positiveEn: 'Deep intuition, wisdom, sensitivity', negative: 'Замкненість, пасивність', negativeEn: 'Withdrawal, passivity', advice: 'Довіряйте своїй інтуїції та розвивайте внутрішню мудрість', adviceEn: 'Trust your intuition and cultivate inner wisdom' },
  { id: 3,  name: 'Імператриця',       arcana: 'The Empress',        planet: 'Венера', planetEn: 'Venus', keywords: ['творчість','достаток','краса'], keywordsEn: ['creativity','abundance','beauty'], positive: 'Творчість, материнство, достаток, гармонія', positiveEn: 'Creativity, nurturing, abundance, harmony', negative: 'Лінь, залежність від комфорту', negativeEn: 'Laziness, dependence on comfort', advice: 'Розкривайте свій творчий потенціал та створюйте красу навколо себе', adviceEn: 'Unlock your creative potential and create beauty around you' },
  { id: 4,  name: 'Імператор',         arcana: 'The Emperor',        planet: 'Марс', planetEn: 'Mars', keywords: ['влада','структура','стабільність'], keywordsEn: ['authority','structure','stability'], positive: 'Стабільність, відповідальність, організованість', positiveEn: 'Stability, responsibility, organization', negative: 'Тиранія, жорсткість, контроль', negativeEn: 'Tyranny, rigidity, control', advice: 'Будуйте структуру та порядок у житті, беріть відповідальність', adviceEn: 'Build structure and order in your life, take responsibility' },
  { id: 5,  name: 'Ієрофант',          arcana: 'The Hierophant',     planet: 'Юпітер', planetEn: 'Jupiter', keywords: ['вчитель','традиції','духовність'], keywordsEn: ['teacher','tradition','spirituality'], positive: 'Мудрість, наставництво, духовний розвиток', positiveEn: 'Wisdom, mentorship, spiritual growth', negative: 'Догматизм, моралізаторство', negativeEn: 'Dogmatism, moralizing', advice: 'Шукайте знання та діліться мудрістю з іншими', adviceEn: 'Seek knowledge and share wisdom with others' },
  { id: 6,  name: 'Закохані',          arcana: 'The Lovers',         planet: 'Венера', planetEn: 'Venus', keywords: ['любов','вибір','гармонія'], keywordsEn: ['love','choice','harmony'], positive: 'Любов, гармонія у стосунках, правильний вибір', positiveEn: 'Love, harmony in relationships, right choice', negative: 'Нерішучість, залежність', negativeEn: 'Indecisiveness, dependency', advice: 'Приймайте рішення серцем, будуйте гармонійні стосунки', adviceEn: 'Make decisions with your heart, build harmonious relationships' },
  { id: 7,  name: 'Колісниця',         arcana: 'The Chariot',        planet: 'Марс', planetEn: 'Mars', keywords: ['перемога','рух','амбіції'], keywordsEn: ['victory','movement','ambition'], positive: 'Перемога, рух вперед, сила волі, успіх', positiveEn: 'Victory, moving forward, willpower, success', negative: 'Агресія, нетерпіння', negativeEn: 'Aggression, impatience', advice: 'Рухайтесь до мети з рішучістю, контролюйте свої імпульси', adviceEn: 'Move toward your goal with determination, control your impulses' },
  { id: 8,  name: 'Справедливість',    arcana: 'Justice',            planet: 'Сатурн', planetEn: 'Saturn', keywords: ['баланс','карма','закон'], keywordsEn: ['balance','karma','law'], positive: 'Справедливість, баланс, чесність', positiveEn: 'Justice, balance, honesty', negative: 'Осудливість, надмірна критичність', negativeEn: 'Judgmentalism, excessive criticism', advice: 'Дотримуйтесь балансу та будьте чесні з собою і іншими', adviceEn: 'Maintain balance and be honest with yourself and others' },
  { id: 9,  name: 'Відлюдник',         arcana: 'The Hermit',         planet: 'Нептун', planetEn: 'Neptune', keywords: ['самопізнання','мудрість','самотність'], keywordsEn: ['self-discovery','wisdom','solitude'], positive: 'Глибоке самопізнання, мудрість, духовний пошук', positiveEn: 'Deep self-discovery, wisdom, spiritual quest', negative: 'Ізоляція, відчуженість', negativeEn: 'Isolation, alienation', advice: 'Знаходьте час для самопізнання та внутрішнього розвитку', adviceEn: 'Find time for self-discovery and inner growth' },
  { id: 10, name: 'Колесо Фортуни',    arcana: 'Wheel of Fortune',   planet: 'Юпітер', planetEn: 'Jupiter', keywords: ['доля','цикли','удача'], keywordsEn: ['destiny','cycles','luck'], positive: 'Удача, нові можливості, позитивні зміни', positiveEn: 'Luck, new opportunities, positive changes', negative: 'Непостійність, фаталізм', negativeEn: 'Instability, fatalism', advice: 'Приймайте зміни як частину життя та використовуйте можливості', adviceEn: 'Embrace change as part of life and seize opportunities' },
  { id: 11, name: 'Сила',              arcana: 'Strength',           planet: 'Сонце', planetEn: 'Sun', keywords: ['мужність','терпіння','внутрішня сила'], keywordsEn: ['courage','patience','inner strength'], positive: 'Внутрішня сила, мужність, терпіння, стійкість', positiveEn: 'Inner strength, courage, patience, resilience', negative: 'Слабкість, страхи', negativeEn: 'Weakness, fears', advice: 'Розвивайте внутрішню силу та мужність через терпіння', adviceEn: 'Develop inner strength and courage through patience' },
  { id: 12, name: 'Повішений',         arcana: 'The Hanged Man',     planet: 'Нептун', planetEn: 'Neptune', keywords: ['жертва','пауза','новий погляд'], keywordsEn: ['sacrifice','pause','new perspective'], positive: 'Нові перспективи, жертовність, духовне переродження', positiveEn: 'New perspectives, sacrifice, spiritual rebirth', negative: 'Застій, пасивність', negativeEn: 'Stagnation, passivity', advice: 'Іноді потрібно зупинитися щоб побачити нові можливості', adviceEn: 'Sometimes you need to pause to see new possibilities' },
  { id: 13, name: 'Смерть',            arcana: 'Death',              planet: 'Плутон', planetEn: 'Pluto', keywords: ['трансформація','завершення','оновлення'], keywordsEn: ['transformation','endings','renewal'], positive: 'Трансформація, оновлення, звільнення від старого', positiveEn: 'Transformation, renewal, release from the old', negative: 'Страх змін, болісні закінчення', negativeEn: 'Fear of change, painful endings', advice: 'Приймайте завершення як початок нового етапу', adviceEn: 'Accept endings as the beginning of a new chapter' },
  { id: 14, name: 'Помірність',        arcana: 'Temperance',         planet: 'Сатурн', planetEn: 'Saturn', keywords: ['гармонія','терпіння','баланс'], keywordsEn: ['harmony','patience','balance'], positive: 'Гармонія, помірність, терпіння, баланс', positiveEn: 'Harmony, temperance, patience, balance', negative: 'Надмірна стриманість', negativeEn: 'Excessive restraint', advice: 'Знаходьте золоту середину та будьте терплячі', adviceEn: 'Find the golden mean and be patient' },
  { id: 15, name: 'Диявол',            arcana: 'The Devil',          planet: 'Сатурн', planetEn: 'Saturn', keywords: ['спокуса','залежність','тінь'], keywordsEn: ['temptation','addiction','shadow'], positive: 'Пристрасть, харизма, матеріальний успіх', positiveEn: 'Passion, charisma, material success', negative: 'Залежності, маніпуляції, жадібність', negativeEn: 'Addictions, manipulation, greed', advice: 'Усвідомлюйте свої тіньові сторони та звільняйтесь від залежностей', adviceEn: 'Acknowledge your shadow side and free yourself from addictions' },
  { id: 16, name: 'Вежа',              arcana: 'The Tower',          planet: 'Марс', planetEn: 'Mars', keywords: ['руйнування','пробудження','звільнення'], keywordsEn: ['destruction','awakening','liberation'], positive: 'Раптове пробудження, звільнення, руйнування ілюзій', positiveEn: 'Sudden awakening, liberation, shattering of illusions', negative: 'Катастрофа, шок, конфлікти', negativeEn: 'Catastrophe, shock, conflicts', advice: 'Приймайте раптові зміни як можливість для зростання', adviceEn: 'Embrace sudden changes as an opportunity for growth' },
  { id: 17, name: 'Зірка',             arcana: 'The Star',           planet: 'Уран', planetEn: 'Uranus', keywords: ['надія','натхнення','зцілення'], keywordsEn: ['hope','inspiration','healing'], positive: 'Надія, натхнення, творчість, духовне зцілення', positiveEn: 'Hope, inspiration, creativity, spiritual healing', negative: 'Відірваність від реальності', negativeEn: 'Disconnection from reality', advice: 'Тримайте надію та вірте у свою зірку, слідуйте мрії', adviceEn: 'Hold on to hope and believe in your star, follow your dream' },
  { id: 18, name: 'Місяць',            arcana: 'The Moon',           planet: 'Місяць', planetEn: 'Moon', keywords: ['ілюзії','підсвідомість','тривога'], keywordsEn: ['illusions','subconscious','anxiety'], positive: 'Інтуїція, уява, глибоке підсвідоме знання', positiveEn: 'Intuition, imagination, deep subconscious knowledge', negative: 'Ілюзії, страхи, тривога', negativeEn: 'Illusions, fears, anxiety', advice: 'Працюйте зі своїм підсвідомим та не піддавайтесь ілюзіям', adviceEn: 'Work with your subconscious and do not succumb to illusions' },
  { id: 19, name: 'Сонце',             arcana: 'The Sun',            planet: 'Сонце', planetEn: 'Sun', keywords: ['радість','успіх','життєва сила'], keywordsEn: ['joy','success','vitality'], positive: 'Радість, успіх, оптимізм, щастя', positiveEn: 'Joy, success, optimism, happiness', negative: 'Самовпевненість, поверховість', negativeEn: 'Overconfidence, superficiality', advice: 'Сяйте як сонце — діліться радістю та енергією з іншими', adviceEn: 'Shine like the sun — share joy and energy with others' },
  { id: 20, name: 'Суд',               arcana: 'Judgement',          planet: 'Плутон', planetEn: 'Pluto', keywords: ['відродження','призначення','заклик'], keywordsEn: ['rebirth','calling','awakening'], positive: 'Відродження, прийняття призначення, трансформація', positiveEn: 'Rebirth, embracing your calling, transformation', negative: 'Самоосуд, невміння відпускати', negativeEn: 'Self-judgment, inability to let go', advice: 'Прислухайтесь до внутрішнього заклику та приймайте своє призначення', adviceEn: 'Listen to your inner calling and embrace your destiny' },
  { id: 21, name: 'Світ',              arcana: 'The World',          planet: 'Сатурн', planetEn: 'Saturn', keywords: ['завершення','цілісність','досягнення'], keywordsEn: ['completion','wholeness','achievement'], positive: 'Завершеність, досягнення мети, гармонія', positiveEn: 'Completion, goal achievement, harmony', negative: 'Стагнація, страх завершення', negativeEn: 'Stagnation, fear of completion', advice: 'Святкуйте свої досягнення та готуйтесь до нового циклу', adviceEn: 'Celebrate your achievements and prepare for a new cycle' },
  { id: 22, name: 'Блазень',           arcana: 'The Fool',           planet: 'Уран', planetEn: 'Uranus', keywords: ['свобода','початок','довіра'], keywordsEn: ['freedom','beginning','trust'], positive: 'Свобода, нові початки, спонтанність', positiveEn: 'Freedom, new beginnings, spontaneity', negative: 'Безвідповідальність, хаос', negativeEn: 'Irresponsibility, chaos', advice: 'Будьте відкриті до нового і довіряйте процесу життя', adviceEn: 'Be open to the new and trust the process of life' },
];

export const FALLBACK_TAROT_CARDS: TarotCard[] = [
  {
    id: 0, name: 'The Fool', nameUk: 'Блазень', arcana: 'major',
    keywords: ['початок','свобода','пригода','безтурботність'],
    keywordsEn: ['new beginnings','freedom','adventure','carefree spirit'],
    description: 'Блазень — перша карта Великих Арканів і символ чистого потенціалу. Він стоїть на краю прірви, але його серце сповнене радості та довіри до Всесвіту. Блазень уособлює початок будь-якої подорожі — ту мить, коли ми ще не знаємо, що попереду, але готові стрибнути. Це архетип нескінченної свободи, дитячої цікавості та відкритості до всього нового.',
    descriptionEn: 'The Fool is the first card of the Major Arcana and a symbol of pure potential. He stands at the edge of a cliff, yet his heart is filled with joy and trust in the Universe. The Fool embodies the beginning of any journey — that moment when we do not yet know what lies ahead, but are ready to leap. This is the archetype of boundless freedom, childlike curiosity, and openness to all that is new.',
    upright: 'Новий початок, необмежені можливості, авантюризм, невинність. Ви стоїте на порозі чогось нового і захоплюючого. Час діяти спонтанно, довіряти інтуїції та відкинути страх помилок. Найкращі пригоди починаються з одного сміливого кроку.',
    uprightEn: 'A new beginning, unlimited possibilities, adventurousness, innocence. You stand on the threshold of something new and exhilarating. It is time to act spontaneously, trust your intuition, and cast aside the fear of mistakes. The greatest adventures begin with a single brave step.',
    reversed: 'Безрозсудність, безвідповідальність, ризик без обдумування, наївність. Можливо, ви ігноруєте важливі сигнали або уникаєте відповідальності. Зупиніться та оцініть ситуацію тверезо.',
    reversedEn: 'Recklessness, irresponsibility, risk without forethought, naivety. You may be ignoring important signals or avoiding responsibility. Pause and assess the situation with a clear mind.',
    advice: 'Довіртеся інтуїції та зробіть перший крок. Не чекайте ідеальних умов — вони ніколи не настануть. Беріть від життя максимум, але залишайтеся уважними до реальності.',
    adviceEn: 'Trust your intuition and take the first step. Do not wait for perfect conditions — they will never arrive. Embrace life to the fullest, but remain mindful of reality.',
    loveAdvice: 'У коханні Блазень закликає відкритися новим стосункам без страху і упереджень. Якщо ви вже в парі — внесіть у стосунки свіжість та грайливість. Для самотніх — несподівана зустріч може змінити все.',
    loveAdviceEn: 'In love, The Fool calls you to open yourself to new relationships without fear or prejudice. If you are already in a partnership — bring freshness and playfulness into the bond. For the unattached — an unexpected encounter may change everything.',
    careerAdvice: 'Ідеальний час для нового проєкту, зміни кар\'єри або запуску власної справи. Ваша енергія та ентузіазм заразливі. Не дозвольте страху невдачі зупинити вас.',
    careerAdviceEn: 'The ideal time for a new project, a career change, or launching your own venture. Your energy and enthusiasm are contagious. Do not let the fear of failure hold you back.',
    financeAdvice: 'Будьте відкритим до нестандартних можливостей заробітку. Уникайте імпульсивних витрат та ризикованих вкладень без аналізу. Довіра до Всесвіту добра, але фінансова грамотність теж важлива.',
    financeAdviceEn: 'Be open to unconventional earning opportunities. Avoid impulsive spending and risky investments made without analysis. Trust in the Universe is good, but financial literacy is equally important.',
    healthAdvice: 'Тіло потребує руху та свіжого повітря. Спробуйте новий вид спорту або фізичної активності. Здоров\'я — це також про радість і легкість буття. Уникайте надмірного стресу.',
    healthAdviceEn: 'Your body craves movement and fresh air. Try a new sport or physical activity. Health is also about joy and lightness of being. Avoid excessive stress.',
    spiritualAdvice: 'Духовно Блазень символізує початок нового шляху самопізнання. Відкрийтесь для нових практик, медитацій чи вчень. Ваша душа готова до пробудження.',
    spiritualAdviceEn: 'Spiritually, The Fool symbolizes the beginning of a new path of self-discovery. Open yourself to new practices, meditations, or teachings. Your soul is ready for awakening.',
    yesNo: 'yes', element: 'Повітря', elementEn: 'Air', planet: 'Уран', planetEn: 'Uranus',
  },
  {
    id: 1, name: 'The Magician', nameUk: 'Маг', arcana: 'major',
    keywords: ['воля','майстерність','маніфестація','ресурси'],
    keywordsEn: ['willpower','mastery','manifestation','resources'],
    description: 'Маг — майстер маніфестації, людина, яка перетворює думки на реальність. На його столі лежать усі чотири символи — жезл, кубок, меч і пентакль, що означають владу над усіма сферами буття. Маг знає: у нас є всі необхідні ресурси. Це карта сили волі, концентрації та цілеспрямованості.',
    descriptionEn: 'The Magician is a master of manifestation — one who transforms thoughts into reality. Upon his table lie all four symbols — wand, cup, sword, and pentacle — signifying dominion over every realm of existence. The Magician knows: we already possess all the resources we need. This is the card of willpower, concentration, and purpose.',
    upright: 'Ви маєте всі інструменти для досягнення мети. Час діяти рішуче та цілеспрямовано. Ваша воля, інтелект та харизма на піку. Маніфестуйте бажане через конкретні дії — думки матеріалізуються швидко.',
    uprightEn: 'You possess all the tools needed to achieve your goal. It is time to act decisively and with purpose. Your willpower, intellect, and charisma are at their peak. Manifest your desires through concrete action — thoughts materialize swiftly.',
    reversed: 'Маніпуляція, слабка воля, нереалізований потенціал, обман. Можливо, ви або хтось інший використовує таланти нечесно. Страх невдачі може блокувати вашу силу.',
    reversedEn: 'Manipulation, weak will, unrealized potential, deception. You or someone else may be using talents dishonestly. Fear of failure may be blocking your power.',
    advice: 'Використайте свої таланти та ресурси на повну. Зосередьтеся на одній чіткій меті та рухайтеся до неї системно. Ваш потенціал набагато більший, ніж ви думаєте.',
    adviceEn: 'Harness your talents and resources to their fullest. Focus on one clear goal and move toward it systematically. Your potential is far greater than you realize.',
    loveAdvice: 'У стосунках ви привабливі та харизматичні. Будьте щирими у намірах — партнер відчуває нещирість. Для одиноких: ваша магнетична енергія притягує цікавих людей.',
    loveAdviceEn: 'In relationships, you are attractive and charismatic. Be sincere in your intentions — your partner senses insincerity. For the unattached: your magnetic energy draws fascinating people toward you.',
    careerAdvice: 'Час продемонструвати свої здібності. Ваші навички та знання помічені. Беріть ініціативу, пропонуйте ідеї та не бійтеся лідерства.',
    careerAdviceEn: 'It is time to showcase your abilities. Your skills and knowledge have been noticed. Take the initiative, propose ideas, and do not fear leadership.',
    financeAdvice: 'Зараз сприятливий час для інвестицій та нових фінансових стратегій. Дійте з розумом та впевненістю — гроші йдуть до тих, хто знає, чого хоче.',
    financeAdviceEn: 'Now is a favorable time for investments and new financial strategies. Act with wisdom and confidence — money flows to those who know what they want.',
    healthAdvice: 'Ментальне здоров\'я — ваш головний ресурс. Думки впливають на тіло. Практикуйте позитивне мислення та медитацію.',
    healthAdviceEn: 'Mental health is your greatest resource. Thoughts influence the body. Practice positive thinking and meditation.',
    spiritualAdvice: 'Ви здатні створювати свою реальність силою думки та наміру. Вивчайте практики роботи з намірами та візуалізацію. Ваш зв\'язок з вищими силами зміцнюється через свідоме творення.',
    spiritualAdviceEn: 'You are capable of creating your reality through the power of thought and intention. Study practices of intention-setting and visualization. Your connection with higher forces strengthens through conscious creation.',
    yesNo: 'yes', element: 'Вогонь', elementEn: 'Fire', planet: 'Меркурій', planetEn: 'Mercury',
  },
  {
    id: 2, name: 'The High Priestess', nameUk: 'Жриця', arcana: 'major',
    keywords: ['інтуїція','таємниця','підсвідомість','мудрість'],
    keywordsEn: ['intuition','mystery','subconscious','wisdom'],
    description: 'Жриця — хранителька таємниць та символ глибинної мудрості. Вона сидить між двома колонами — світлом і тінню. Жриця уособлює підсвідомість, інтуїцію та внутрішнє знання, що виходить за межі логіки. Це запрошення зупинитися і довіритися тому, що серце знає без слів.',
    descriptionEn: 'The High Priestess is the keeper of mysteries and a symbol of profound wisdom. She sits between two pillars — light and shadow. The Priestess embodies the subconscious, intuition, and inner knowledge that transcends logic. This is an invitation to pause and trust what the heart knows without words.',
    upright: 'Прислухайтесь до внутрішнього голосу. Ваша інтуїція зараз на піку та надсилає важливі сигнали. Можливо, є приховані обставини, які ще не розкрилися. Терпіння та спостереження принесуть більше, ніж активні дії.',
    uprightEn: 'Listen to your inner voice. Your intuition is at its peak now and sending important signals. There may be hidden circumstances that have not yet revealed themselves. Patience and observation will yield more than active pursuit.',
    reversed: 'Ігнорування інтуїції, прихована інформація, поверховість. Ви надто покладаєтеся на розум та ігноруєте відчуття. Час зупинитися та прислухатися до внутрішнього голосу.',
    reversedEn: 'Ignoring intuition, hidden information, superficiality. You are relying too heavily on the mind and dismissing your feelings. It is time to stop and listen to your inner voice.',
    advice: 'Медитуйте та довіряйте своїй інтуїції. Ведіть щоденник снів та інтуїтивних відчуттів. Відповідь, яку ви шукаєте, вже є всередині вас.',
    adviceEn: 'Meditate and trust your intuition. Keep a journal of dreams and intuitive impressions. The answer you seek already resides within you.',
    loveAdvice: 'Глибокий зв\'язок на рівні душ. Жриця закликає шукати справжнього духовного єднання. Прислухайтеся до своєї інтуїції щодо партнера — вона не бреше.',
    loveAdviceEn: 'A deep connection at the soul level. The High Priestess calls you to seek genuine spiritual union. Listen to your intuition about your partner — it does not lie.',
    careerAdvice: 'Прислухайтесь до внутрішніх відчуттів щодо кар\'єрних рішень. Зараз не час для гучних заяв — збирайте інформацію та аналізуйте.',
    careerAdviceEn: 'Heed your inner feelings regarding career decisions. Now is not the time for bold declarations — gather information and analyze.',
    financeAdvice: 'Будьте обережні з фінансовими рішеннями — щось може бути приховано. Не поспішайте з вкладеннями. Вивчіть усі деталі, перш ніж підписувати угоди.',
    financeAdviceEn: 'Be cautious with financial decisions — something may be hidden. Do not rush into investments. Study every detail before signing agreements.',
    healthAdvice: 'Звертайте увагу на тонкі сигнали тіла. Практикуйте йогу, медитацію. Загадкові симптоми можуть мати емоційне коріння — досліджуйте глибше.',
    healthAdviceEn: 'Pay attention to the subtle signals of your body. Practice yoga and meditation. Mysterious symptoms may have emotional roots — investigate deeper.',
    spiritualAdvice: 'Ваш духовний розвиток відбувається у глибині — в снах, відчуттях, тихих прозріннях. Практикуйте медитацію, вивчайте нумерологію та астрологію.',
    spiritualAdviceEn: 'Your spiritual development unfolds in the depths — in dreams, sensations, and quiet revelations. Practice meditation, study numerology and astrology.',
    yesNo: 'maybe', element: 'Вода', elementEn: 'Water', planet: 'Місяць', planetEn: 'Moon',
  },
  {
    id: 3, name: 'The Empress', nameUk: 'Імператриця', arcana: 'major',
    keywords: ['достаток','краса','родючість','турбота'],
    keywordsEn: ['abundance','beauty','fertility','nurturing'],
    description: 'Імператриця — богиня природи, краси та родючості. Вона сидить у розкішному саду, оточена зрілими плодами та квітами — символами достатку та творчого розквіту. Ця карта уособлює материнську енергію Землі, чуттєвість та силу творення. Вона нагадує про силу в ніжності.',
    descriptionEn: 'The Empress is the goddess of nature, beauty, and fertility. She sits in a lush garden, surrounded by ripe fruits and flowers — symbols of abundance and creative flourishing. This card embodies the maternal energy of the Earth, sensuality, and the power of creation. She reminds us of the strength found in tenderness.',
    upright: 'Пора розквіту та достатку. Творчість, краса та любов у всьому їх вираженні. Час плекати свої проєкти, стосунки та власне тіло з любов\'ю. Все, що ви вкладаєте з любов\'ю, приноситиме щедрі плоди.',
    uprightEn: 'A season of flourishing and abundance. Creativity, beauty, and love in all their expressions. It is time to nurture your projects, relationships, and your own body with love. Everything you invest with love shall bear generous fruit.',
    reversed: 'Залежність, надмірна турбота, блокування творчості. Можливо, ви нехтуєте собою або зайво контролюєте інших. Відновіть баланс між даванням і отриманням.',
    reversedEn: 'Dependency, excessive caretaking, creative blockage. You may be neglecting yourself or overly controlling others. Restore the balance between giving and receiving.',
    advice: 'Оточіть себе красою та природою. Плекайте свої творчі проєкти з терпінням та любов\'ю. Дозвольте собі отримувати так само щедро, як ви даєте.',
    adviceEn: 'Surround yourself with beauty and nature. Nurture your creative projects with patience and love. Allow yourself to receive as generously as you give.',
    loveAdvice: 'Стосунки наповнені ніжністю, пристрастю та глибокою прив\'язаністю. Час для зближення та романтики. Для тих, хто мріє про сім\'ю — ця карта може вказувати на вагітність або нові стосунки.',
    loveAdviceEn: 'Relationships are filled with tenderness, passion, and deep devotion. A time for closeness and romance. For those dreaming of family — this card may indicate pregnancy or a new relationship.',
    careerAdvice: 'Творчі проєкти принесуть успіх та визнання. Ваша природна харизма — ваша сила. Сфери мистецтва, дизайну та краси особливо сприятливі.',
    careerAdviceEn: 'Creative projects will bring success and recognition. Your natural charisma is your strength. The fields of art, design, and beauty are especially favorable.',
    financeAdvice: 'Матеріальний достаток зростає. Зараз сприятливий час для вкладень у нерухомість або творчий бізнес. Ваш добробут пов\'язаний з тим, наскільки ви цінуєте те, що маєте.',
    financeAdviceEn: 'Material prosperity is growing. Now is a favorable time for investments in real estate or creative business. Your well-being is tied to how much you appreciate what you already have.',
    healthAdvice: 'Тіло потребує ніжності та турботи. Зверніть увагу на харчування, відпочинок та час на природі. Масаж, ванни, ароматерапія — все це зціляє.',
    healthAdviceEn: 'Your body needs tenderness and care. Pay attention to nutrition, rest, and time in nature. Massage, baths, aromatherapy — all of these are healing.',
    spiritualAdvice: 'Ваш духовний шлях — через красу, природу та тіло. Практикуйте усвідомлене харчування та прогулянки на природі. Богиня в вас хоче бути побаченою.',
    spiritualAdviceEn: 'Your spiritual path leads through beauty, nature, and the body. Practice mindful eating and walks in nature. The goddess within you wishes to be seen.',
    yesNo: 'yes', element: 'Земля', elementEn: 'Earth', planet: 'Венера', planetEn: 'Venus',
  },
  {
    id: 4, name: 'The Emperor', nameUk: 'Імператор', arcana: 'major',
    keywords: ['влада','структура','стабільність','авторитет'],
    keywordsEn: ['authority','structure','stability','leadership'],
    description: 'Імператор — символ влади, структури та земного порядку. Він сидить на кам\'яному троні, його погляд сповнений рішучості та авторитету. Ця карта уособлює чоловічу силу в її найкращому прояві: захист, стабільність та лідерство. Нагадує про важливість дисципліни та відповідальності.',
    descriptionEn: 'The Emperor is the symbol of authority, structure, and earthly order. He sits upon a stone throne, his gaze filled with determination and command. This card embodies masculine power at its finest: protection, stability, and leadership. It reminds us of the importance of discipline and responsibility.',
    upright: 'Час встановити порядок і стабільність. Ваш авторитет та лідерські якості на піку. Будуйте тривалі структури — в бізнесі, стосунках чи особистому житті. Чіткі правила та межі принесуть безпеку.',
    uprightEn: 'It is time to establish order and stability. Your authority and leadership qualities are at their peak. Build lasting structures — in business, relationships, or personal life. Clear rules and boundaries will bring security.',
    reversed: 'Тиранія, жорсткість, надмірний контроль, втрата авторитету. Можливо, хтось зловживає владою. Жорсткість заважає гнучкості та росту.',
    reversedEn: 'Tyranny, rigidity, excessive control, loss of authority. Someone may be abusing power. Rigidity hinders flexibility and growth.',
    advice: 'Встановіть чіткі межі та правила — для себе та інших. Будьте відповідальними лідерами, а не тиранами. Структура та дисципліна — ваші найкращі союзники.',
    adviceEn: 'Set clear boundaries and rules — for yourself and others. Be a responsible leader, not a tyrant. Structure and discipline are your greatest allies.',
    loveAdvice: 'Стабільність і надійність — основа ваших стосунків. Партнер цінує вашу захищаючу силу. Однак стежте, щоб контроль не замінив любов.',
    loveAdviceEn: 'Stability and reliability form the foundation of your relationship. Your partner values your protective strength. However, ensure that control does not replace love.',
    careerAdvice: 'Лідерські якості принесуть успіх. Час брати на себе більше відповідальності або відкривати власну справу. Стратегічне мислення та дисципліна — ваша перевага.',
    careerAdviceEn: 'Leadership qualities will bring success. It is time to take on more responsibility or start your own enterprise. Strategic thinking and discipline are your edge.',
    financeAdvice: 'Фінансова стабільність досягається через планування та дисципліну. Складіть чіткий бюджет та дотримуйтесь його. Консервативні інвестиції принесуть стабільний результат.',
    financeAdviceEn: 'Financial stability is achieved through planning and discipline. Create a clear budget and adhere to it. Conservative investments will yield steady returns.',
    healthAdvice: 'Структура у здоровому способі життя є ключем. Регулярні тренування та режим дня — те, що зараз потрібно. Стежте за кістково-м\'язовою системою та серцем.',
    healthAdviceEn: 'Structure in a healthy lifestyle is the key. Regular exercise and a daily routine are what is needed now. Monitor your musculoskeletal system and heart.',
    spiritualAdvice: 'Ваш духовний шлях потребує дисципліни та регулярної практики. Медитація у визначений час та щоденні ритуали дадуть стабільний результат. Заземлення — ваш інструмент.',
    spiritualAdviceEn: 'Your spiritual path requires discipline and regular practice. Meditation at set times and daily rituals will yield steady results. Grounding is your instrument.',
    yesNo: 'yes', element: 'Вогонь', elementEn: 'Fire', planet: 'Марс', planetEn: 'Mars',
  },
  {
    id: 5, name: 'The Hierophant', nameUk: 'Ієрофант', arcana: 'major',
    keywords: ['традиції','духовність','наставник','навчання'],
    keywordsEn: ['tradition','spirituality','mentor','learning'],
    description: 'Ієрофант — провідник між небесним і земним, хранитель священних знань та традицій. Він символізує інституційну мудрість та духовне наставництво. Ця карта запрошує нас шукати вчителя або самим стати джерелом мудрості для інших. Ієрофант нагадує про цінність колективного досвіду людства.',
    descriptionEn: 'The Hierophant is the bridge between the celestial and the earthly, the keeper of sacred knowledge and tradition. He symbolizes institutional wisdom and spiritual mentorship. This card invites us to seek a teacher or to become a source of wisdom for others. The Hierophant reminds us of the value of humanity\'s collective experience.',
    upright: 'Час звернутись до перевірених традицій та мудрості. Шукайте наставника або офіційне навчання. Колективні цінності та усталені структури є вашою опорою.',
    uprightEn: 'It is time to turn to proven traditions and wisdom. Seek a mentor or formal education. Collective values and established structures are your support.',
    reversed: 'Догматизм, бунт проти правил, застарілі переконання. Можливо, традиційні шляхи більше не працюють для вас. Час знайти власну стежку.',
    reversedEn: 'Dogmatism, rebellion against rules, outdated beliefs. Traditional paths may no longer work for you. It is time to find your own trail.',
    advice: 'Шукайте духовне наставництво або поділіться своєю мудрістю. Навчайтеся від тих, хто пройшов цей шлях раніше. Залишайтеся відкритими до нових ідей.',
    adviceEn: 'Seek spiritual mentorship or share your own wisdom. Learn from those who have walked this path before. Remain open to new ideas.',
    loveAdvice: 'Традиційні цінності у стосунках. Стабільні, офіційні зв\'язки мають силу зараз. Для одиноких — серйозні стосунки ймовірніші, ніж флірт.',
    loveAdviceEn: 'Traditional values in relationships. Stable, committed bonds hold power now. For the unattached — a serious relationship is more likely than a casual fling.',
    careerAdvice: 'Дотримуйтесь встановлених правил та протоколів. Наставник або ментор може відкрити нові двері. Освіта та сертифікація підвищать вашу цінність.',
    careerAdviceEn: 'Follow established rules and protocols. A mentor or guide may open new doors. Education and certification will increase your value.',
    financeAdvice: 'Дотримуйтесь перевірених фінансових стратегій. Не ризикуйте з авантюрними схемами — стабільність важливіша за швидке збагачення.',
    financeAdviceEn: 'Adhere to proven financial strategies. Do not risk adventurous schemes — stability is more important than quick riches.',
    healthAdvice: 'Традиційна медицина та перевірені методи лікування мають перевагу. Регулярні огляди у лікаря дадуть ясність.',
    healthAdviceEn: 'Traditional medicine and proven treatment methods have the advantage. Regular medical checkups will bring clarity.',
    spiritualAdvice: 'Структурована духовна практика — медитація за традицією, молитва, вивчення священних текстів — дасть глибоке коріння. Шукайте спільноту однодумців.',
    spiritualAdviceEn: 'Structured spiritual practice — traditional meditation, prayer, study of sacred texts — will give you deep roots. Seek a community of like-minded souls.',
    yesNo: 'yes', element: 'Земля', elementEn: 'Earth', planet: 'Юпітер', planetEn: 'Jupiter',
  },
  {
    id: 6, name: 'The Lovers', nameUk: 'Закохані', arcana: 'major',
    keywords: ['любов','вибір','гармонія','союз'],
    keywordsEn: ['love','choice','harmony','union'],
    description: 'Закохані символізують не лише романтичне кохання, а й усі важливі вибори в житті. Це момент, коли ми стоїмо на роздоріжжі та маємо вирішити, що для нас справді важливо. Закохані уособлюють гармонію протилежностей та силу вибору, зробленого з любов\'ю та чесністю.',
    descriptionEn: 'The Lovers symbolize not only romantic love but all the significant choices in life. This is the moment when we stand at a crossroads and must decide what truly matters to us. The Lovers embody the harmony of opposites and the power of a choice made with love and honesty.',
    upright: 'Важливий вибір попереду. Стосунки, гармонія та єднання на всіх рівнях. Серце та розум мають погодитися. Виберіть те, що резонує з вашими глибинними цінностями.',
    uprightEn: 'An important choice lies ahead. Relationships, harmony, and unity on all levels. Heart and mind must align. Choose that which resonates with your deepest values.',
    reversed: 'Дисгармонія, неправильний вибір, розрив. Зовнішній тиск впливає на ваші рішення. Або ж ви уникаєте важкого, але необхідного вибору.',
    reversedEn: 'Disharmony, a wrong choice, separation. External pressure is influencing your decisions. Or perhaps you are avoiding a difficult but necessary choice.',
    advice: 'Приймайте рішення з любов\'ю та чесністю. Справжній союз будується на взаємній повазі та спільних цінностях.',
    adviceEn: 'Make decisions with love and honesty. A true union is built upon mutual respect and shared values.',
    loveAdvice: 'Глибоке кохання та сильний зв\'язок. Ця карта — добрий знак для романтичних стосунків. Час для важливих рішень: переїзд разом, заручини, шлюб.',
    loveAdviceEn: 'Deep love and a strong bond. This card is an auspicious sign for romantic relationships. A time for important decisions: moving in together, engagement, marriage.',
    careerAdvice: 'Вибирайте роботу, яка резонує з вашими цінностями. Співпраця та партнерство принесуть більше, ніж самотня праця.',
    careerAdviceEn: 'Choose work that resonates with your values. Collaboration and partnership will yield more than solitary labor.',
    financeAdvice: 'Фінансові рішення мають відображати ваші справжні пріоритети. Якщо думаєте про спільний бюджет — перевірте, чи збігаються ваші цінності.',
    financeAdviceEn: 'Financial decisions should reflect your true priorities. If considering a shared budget — verify that your values are aligned.',
    healthAdvice: 'Закохані нагадують про баланс тіла і душі. Стосунки впливають на ваше фізичне самопочуття. Зверніть увагу на серце та спину.',
    healthAdviceEn: 'The Lovers remind us of the balance between body and soul. Relationships affect your physical well-being. Pay attention to your heart and spine.',
    spiritualAdvice: 'Духовна єдність — найвищий прояв цієї карти. Шукайте партнера на духовному шляху. Практикуйте медитації для пари.',
    spiritualAdviceEn: 'Spiritual unity is the highest expression of this card. Seek a partner on the spiritual path. Practice partner meditations.',
    yesNo: 'yes', element: 'Повітря', elementEn: 'Air', planet: 'Венера', planetEn: 'Venus',
  },
  {
    id: 7, name: 'The Chariot', nameUk: 'Колісниця', arcana: 'major',
    keywords: ['перемога','рух','воля','контроль'],
    keywordsEn: ['victory','movement','willpower','control'],
    description: 'Колісниця — карта перемоги через силу волі та рішучість. Возниця управляє двома сфінксами, що тягнуть у різні боки — символ уміння направляти протилежні сили до єдиної мети. Перемога досягається не грубою силою, а дисципліною та внутрішньою злагодою.',
    descriptionEn: 'The Chariot is the card of victory through willpower and determination. The charioteer commands two sphinxes pulling in opposite directions — a symbol of the ability to direct opposing forces toward a single goal. Victory is achieved not through brute force, but through discipline and inner harmony.',
    upright: 'Перемога через силу волі та рішучість. Ви долаєте перешкоди та рухаєтесь до мети попри всі труднощі. Ваша дисципліна та фокус є на піку. Час діяти швидко та рішуче.',
    uprightEn: 'Victory through willpower and determination. You are overcoming obstacles and advancing toward your goal despite all difficulties. Your discipline and focus are at their peak. It is time to act swiftly and decisively.',
    reversed: 'Втрата контролю, агресія, поспіх, рух у неправильному напрямку. Зовнішні перемоги без внутрішньої гармонії порожні. Зупиніться та переорієнтуйтесь.',
    reversedEn: 'Loss of control, aggression, haste, movement in the wrong direction. Outward victories without inner harmony are hollow. Stop and reorient yourself.',
    advice: 'Зосередьтеся на меті та рухайтесь без вагань. Дисципліна — ваша суперсила. Управляйте внутрішніми суперечностями, а не пригнічуйте їх.',
    adviceEn: 'Focus on your goal and move forward without hesitation. Discipline is your superpower. Master your inner contradictions rather than suppressing them.',
    loveAdvice: 'Будьте ініціативними у стосунках. Якщо хочете когось — діяйте. Однак бажання перемагати у суперечках руйнує любов — іноді відступити є найбільшою силою.',
    loveAdviceEn: 'Be proactive in relationships. If you desire someone — act. However, the need to win every argument destroys love — sometimes stepping back is the greatest strength.',
    careerAdvice: 'Амбіції та наполегливість приведуть до перемоги. Беріть на себе керівні ролі. Конкуренти відступлять перед вашою рішучістю.',
    careerAdviceEn: 'Ambition and persistence will lead to victory. Take on leadership roles. Competitors will retreat before your determination.',
    financeAdvice: 'Фінансова перемога через дисципліну та стратегію. Агресивніший підхід до фінансів дасть результат. Проте контролюйте витрати під час активних дій.',
    financeAdviceEn: 'Financial victory through discipline and strategy. A more aggressive approach to finances will yield results. However, control your spending during active pursuits.',
    healthAdvice: 'Активний спорт та фізичні навантаження зараз особливо корисні. Ваше тіло здатне на більше, ніж ви думаєте. Підтримуйте баланс між активністю та відпочинком.',
    healthAdviceEn: 'Active sports and physical exertion are especially beneficial now. Your body is capable of more than you think. Maintain a balance between activity and rest.',
    spiritualAdvice: 'Духовний воїн контролює свій розум та емоції. Практикуйте медитацію-воїна або бойові мистецтва як духовну практику. Направте силу волі на служіння вищій меті.',
    spiritualAdviceEn: 'The spiritual warrior controls the mind and emotions. Practice warrior meditation or martial arts as a spiritual discipline. Direct your willpower toward serving a higher purpose.',
    yesNo: 'yes', element: 'Вода', elementEn: 'Water', planet: 'Марс', planetEn: 'Mars',
  },
  {
    id: 8, name: 'Strength', nameUk: 'Сила', arcana: 'major',
    keywords: ['внутрішня сила','мужність','терпіння','співчуття'],
    keywordsEn: ['inner strength','courage','patience','compassion'],
    description: 'Сила показує жінку, що лагідно тримає відкритою пащу лева. Вона перемагає не грубою силою, а любов\'ю та внутрішньою впевненістю. Ця карта уособлює найвищий вид мужності — ту, яка не боїться власних темних сторін та трансформує їх через ніжність. Справжня сила завжди тиха та спокійна.',
    descriptionEn: 'Strength depicts a woman gently holding open the jaws of a lion. She conquers not through brute force, but through love and inner confidence. This card embodies the highest form of courage — one that does not fear its own dark sides and transforms them through tenderness. True strength is always quiet and calm.',
    upright: 'Внутрішня сила та мужність перемагають грубу силу. Ваша терпеливість та ніжність творять чудеса. Ви здатні приборкати будь-які внутрішні страхи та зовнішні виклики.',
    uprightEn: 'Inner strength and courage triumph over brute force. Your patience and gentleness work wonders. You are capable of taming any inner fears and external challenges.',
    reversed: 'Слабкість, невпевненість, страхи, самосаботаж. Ви або надто придушуєте свою силу, або виражаєте її через агресію. Прийміть свою вразливість — у ній є непереможна сила.',
    reversedEn: 'Weakness, self-doubt, fears, self-sabotage. You are either suppressing your power too much or expressing it through aggression. Embrace your vulnerability — within it lies an invincible strength.',
    advice: 'Виявіть свою внутрішню силу через терпіння та любов. Приборкайте свої страхи та темні боки з ніжністю, не боротьбою.',
    adviceEn: 'Reveal your inner strength through patience and love. Tame your fears and dark sides with tenderness, not struggle.',
    loveAdvice: 'Любов вимагає терпіння та ніжності. Ваша сила — в умінні приймати партнера таким, яким він є. Для тих, хто переживає труднощі — стосунки витримають, якщо є справжня любов.',
    loveAdviceEn: 'Love requires patience and tenderness. Your strength lies in the ability to accept your partner as they are. For those enduring difficulties — the relationship will withstand if there is true love.',
    careerAdvice: 'Наполегливість та терпіння принесуть результат. Ваша здатність зберігати спокій під тиском — безцінна якість лідера.',
    careerAdviceEn: 'Perseverance and patience will bring results. Your ability to remain calm under pressure is an invaluable leadership quality.',
    financeAdvice: 'Фінансові труднощі переборні через терпіння та наполегливість. Не панікуйте — ваша стійкість є фінансовою силою. Послідовність принесе стабільність.',
    financeAdviceEn: 'Financial difficulties are surmountable through patience and persistence. Do not panic — your resilience is your financial strength. Consistency will bring stability.',
    healthAdvice: 'Ваше тіло сильніше, ніж ви думаєте. Під час хвороби терпіння та позитивний настрій пришвидшать одужання. Практики на основі дихання зміцнять ваше здоров\'я.',
    healthAdviceEn: 'Your body is stronger than you think. During illness, patience and a positive outlook will hasten recovery. Breath-based practices will fortify your health.',
    spiritualAdvice: 'Найглибша духовна практика — прийняти власну тінь. Медитуйте на темні сторони своєї природи без осуду. Ваша тінь є вашою найбільшою прихованою силою.',
    spiritualAdviceEn: 'The deepest spiritual practice is to embrace your own shadow. Meditate upon the dark sides of your nature without judgment. Your shadow is your greatest hidden power.',
    yesNo: 'yes', element: 'Вогонь', elementEn: 'Fire', planet: 'Сонце', planetEn: 'Sun',
  },
  {
    id: 9, name: 'The Hermit', nameUk: 'Відлюдник', arcana: 'major',
    keywords: ['самопізнання','мудрість','усамітнення','пошук'],
    keywordsEn: ['self-discovery','wisdom','solitude','seeking'],
    description: 'Відлюдник — мудрець, який стоїть на самоті на вершині гори, тримаючи ліхтар. Його світло — не для того, щоб освітити весь шлях, а лише наступний крок. Ця карта уособлює мудрість, здобуту через усамітнення та внутрішній пошук. Він є провідником для інших — тим, хто ділиться мудрістю, здобутою у тиші.',
    descriptionEn: 'The Hermit is a sage who stands alone atop a mountain, holding a lantern. His light is not meant to illuminate the entire path, but only the next step. This card embodies wisdom gained through solitude and inner seeking. He is a guide for others — one who shares the wisdom acquired in silence.',
    upright: 'Час для усамітнення та внутрішнього пошуку. Ваша мудрість зростає у тиші та спогляданні. Відійдіть від суєти, щоб знайти глибинні відповіді. Самотність зараз — це дар.',
    uprightEn: 'A time for solitude and inner seeking. Your wisdom grows in silence and contemplation. Step away from the noise to find profound answers. Solitude right now is a gift.',
    reversed: 'Ізоляція, відлюдькуватість, відмова від допомоги. Можливо, ви відсторонились від людей надміру або навпаки уникаєте необхідного усамітнення.',
    reversedEn: 'Isolation, reclusiveness, refusal of help. You may have withdrawn from people excessively, or conversely, you may be avoiding necessary solitude.',
    advice: 'Знайдіть час для самотності та медитації. Ваша внутрішня мудрість — найцінніший ресурс зараз. Поділіться своїм досвідом з тими, хто шукає.',
    adviceEn: 'Find time for solitude and meditation. Your inner wisdom is your most valuable resource right now. Share your experience with those who seek.',
    loveAdvice: 'Можливо, потрібен час для себе. Зустрівши себе у самотності, ви приваблюєте справжнє кохання. Не вступайте у стосунки, щоб заповнити порожнечу.',
    loveAdviceEn: 'Perhaps you need time for yourself. By finding yourself in solitude, you attract true love. Do not enter relationships merely to fill a void.',
    careerAdvice: 'Самостійна робота або консультативна роль підходять найкраще. Ваш досвід та мудрість цінуються іншими. Менторство та дослідження — ваші сфери.',
    careerAdviceEn: 'Independent work or a consultative role suits you best. Your experience and wisdom are valued by others. Mentorship and research are your domains.',
    financeAdvice: 'Консервативний підхід до фінансів. Порадьтеся з мудрим та досвідченим консультантом. Ваша фінансова незалежність зростає через розважливість.',
    financeAdviceEn: 'A conservative approach to finances. Consult a wise and experienced advisor. Your financial independence grows through prudence.',
    healthAdvice: 'Відпочинок та відновлення — пріоритет. Ваша нервова система потребує тиші. Медитація, ходьба на природі, цифровий детокс — те, що зціляє.',
    healthAdviceEn: 'Rest and recovery are the priority. Your nervous system needs quiet. Meditation, walks in nature, digital detox — these are what heal.',
    spiritualAdvice: 'Ваш духовний шлях — через усамітнення та споглядання. Ретрити та тривалі медитації дадуть глибокий досвід. Ви є провідником для інших — діліться своїм світлом.',
    spiritualAdviceEn: 'Your spiritual path leads through solitude and contemplation. Retreats and prolonged meditations will yield profound experience. You are a guide for others — share your light.',
    yesNo: 'maybe', element: 'Земля', elementEn: 'Earth', planet: 'Меркурій', planetEn: 'Mercury',
  },
  {
    id: 10, name: 'Wheel of Fortune', nameUk: 'Колесо Фортуни', arcana: 'major',
    keywords: ['доля','цикли','удача','зміни'],
    keywordsEn: ['destiny','cycles','fortune','change'],
    description: 'Колесо Фортуни — символ вічного руху циклів та долі. Воно обертається постійно: що було вгорі, опуститься, і навпаки. Ця карта нагадує про непостійність усього земного та про те, що зміни — єдина стала. Однак Колесо Фортуни не про безсилля перед долею, а про прийняття ритму Всесвіту.',
    descriptionEn: 'The Wheel of Fortune is the symbol of the eternal movement of cycles and fate. It turns ceaselessly: what was above shall descend, and vice versa. This card reminds us of the impermanence of all earthly things and that change is the only constant. Yet the Wheel of Fortune is not about helplessness before destiny, but about embracing the rhythm of the Universe.',
    upright: 'Колесо повертається на вашу користь. Удача та сприятливі зміни на порозі. Нова можливість з\'являється несподівано. Скористайтесь моментом — колесо не стоїть на місці.',
    uprightEn: 'The Wheel turns in your favor. Fortune and favorable changes are at the threshold. A new opportunity appears unexpectedly. Seize the moment — the Wheel does not stand still.',
    reversed: 'Невдача, опір змінам, погана удача, зациклення. Ви намагаєтеся зупинити колесо або йдете проти природного плину. Відпустіть контроль.',
    reversedEn: 'Misfortune, resistance to change, bad luck, being stuck in a loop. You are trying to halt the Wheel or going against the natural flow. Release control.',
    advice: 'Приймайте зміни як природну частину циклу. Гнучкість та відкритість до несподіваного — ваша найкраща стратегія зараз.',
    adviceEn: 'Accept change as a natural part of the cycle. Flexibility and openness to the unexpected are your best strategy now.',
    loveAdvice: 'Доля зводить вас з потрібними людьми у потрібний час. Несподівана зустріч може перевернути ваше серце. Відпустіть і довіртеся процесу.',
    loveAdviceEn: 'Fate brings the right people to you at the right time. An unexpected encounter may turn your heart upside down. Let go and trust the process.',
    careerAdvice: 'Нові можливості з\'являться несподівано — будьте готові їх помітити. Зміни у кар\'єрі зараз під захистом Всесвіту.',
    careerAdviceEn: 'New opportunities will appear unexpectedly — be ready to notice them. Career changes are under the protection of the Universe now.',
    financeAdvice: 'Фінансова удача усміхається вам. Зараз сприятливий час для нових інвестицій. Пам\'ятайте: удача непостійна — зберігайте резерви на чорний день.',
    financeAdviceEn: 'Financial fortune smiles upon you. Now is a favorable time for new investments. Remember: luck is fickle — keep reserves for a rainy day.',
    healthAdvice: 'Циклічність притаманна і здоров\'ю. Якщо зараз поганий період — він мине. Якщо добрий — підтримуйте здорові звички.',
    healthAdviceEn: 'Cycles are inherent in health as well. If you are in a difficult period — it shall pass. If a good one — maintain your healthy habits.',
    spiritualAdvice: 'Все у Всесвіті циклічно — і ваш духовний ріст також. Прийміть фази спаду як час накопичення мудрості. Практикуйте відпускання.',
    spiritualAdviceEn: 'Everything in the Universe is cyclical — and your spiritual growth is no exception. Accept phases of decline as times of gathering wisdom. Practice the art of letting go.',
    yesNo: 'yes', element: 'Вогонь', elementEn: 'Fire', planet: 'Юпітер', planetEn: 'Jupiter',
  },
  {
    id: 11, name: 'Justice', nameUk: 'Справедливість', arcana: 'major',
    keywords: ['справедливість','баланс','карма','закон'],
    keywordsEn: ['justice','balance','karma','law'],
    description: 'Справедливість — карта балансу, правди та кармічних законів. Вона сидить із мечем у правій руці та терезами в лівій — символи непідкупного суду та рівноваги. Справедливість нагадує, що кожна дія має наслідки, і що Всесвіт завжди відновлює баланс.',
    descriptionEn: 'Justice is the card of balance, truth, and karmic law. She sits with a sword in her right hand and scales in her left — symbols of incorruptible judgment and equilibrium. Justice reminds us that every action has consequences, and that the Universe always restores balance.',
    upright: 'Справедлива оцінка та правда. Кармічний баланс відновлюється. Ваші дії отримають справедливу оцінку — добрі вчинки повернуться добром. Правда переможе.',
    uprightEn: 'Fair assessment and truth. Karmic balance is being restored. Your actions will receive a just evaluation — good deeds shall return as good. Truth will prevail.',
    reversed: 'Несправедливість, упередженість, нечесність, ухиляння від відповідальності. Кармічний борг не відміняється — він лише відкладається.',
    reversedEn: 'Injustice, bias, dishonesty, avoidance of responsibility. A karmic debt is not cancelled — it is merely postponed.',
    advice: 'Будьте чесні з собою та іншими. Беріть відповідальність за свої вчинки. Справедливе рішення — завжди краще за зручне.',
    adviceEn: 'Be honest with yourself and others. Take responsibility for your actions. A fair decision is always better than a convenient one.',
    loveAdvice: 'Чесність і взаємна повага — основа міцних стосунків. Час для чесної розмови. Карма стосунків проявляється зараз.',
    loveAdviceEn: 'Honesty and mutual respect are the foundation of strong relationships. It is time for an honest conversation. Relationship karma is manifesting now.',
    careerAdvice: 'Юридичні справи вирішаться на вашу користь. Ваша репутація чесного фахівця — ваш актив. Угоди та контракти зараз на вашому боці.',
    careerAdviceEn: 'Legal matters will be resolved in your favor. Your reputation as an honest professional is your asset. Agreements and contracts are on your side now.',
    financeAdvice: 'Фінансові справи потребують чесності та прозорості. Уникайте сірих схем — вони повернуться проблемами.',
    financeAdviceEn: 'Financial matters require honesty and transparency. Avoid grey schemes — they will come back as problems.',
    healthAdvice: 'Зверніть увагу на баланс у стилі життя. Ваші симптоми можуть відображати внутрішній дисбаланс. Чесна оцінка свого здоров\'я принесе ясність.',
    healthAdviceEn: 'Pay attention to balance in your lifestyle. Your symptoms may reflect an inner imbalance. An honest assessment of your health will bring clarity.',
    spiritualAdvice: 'Карма — жива та активна у вашому житті зараз. Практикуйте усвідомленість щодо своїх думок, слів та дій. Чесність перед собою — вища духовна чеснота.',
    spiritualAdviceEn: 'Karma is alive and active in your life right now. Practice mindfulness regarding your thoughts, words, and deeds. Honesty with yourself is the highest spiritual virtue.',
    yesNo: 'yes', element: 'Повітря', elementEn: 'Air', planet: 'Сатурн', planetEn: 'Saturn',
  },
  {
    id: 12, name: 'The Hanged Man', nameUk: 'Повішений', arcana: 'major',
    keywords: ['пауза','жертва','перспектива','прийняття'],
    keywordsEn: ['pause','sacrifice','perspective','surrender'],
    description: 'Повішений висить догори ногами на дереві добровільно, і його обличчя сяє спокоєм. Ця карта говорить про добровільне жертвування — відмову від звичного способу бачення заради глибшого розуміння. Коли перевертаєш картину догори ногами, бачиш її по-іншому.',
    descriptionEn: 'The Hanged Man hangs upside down from a tree by his own will, and his face glows with serenity. This card speaks of voluntary sacrifice — the renunciation of the familiar way of seeing in exchange for deeper understanding. When you turn the picture upside down, you see it differently.',
    upright: 'Час зупинитись і переосмислити. Добровільна пауза відкриє нову перспективу. Відпустіть те, за що тримаєтеся — і побачите картину ширше.',
    uprightEn: 'It is time to pause and reassess. A voluntary stillness will open a new perspective. Let go of what you are clinging to — and you will see the bigger picture.',
    reversed: 'Застій, марна жертва, небажання відпустити, мученицька позиція. Можливо, час вийти з ситуації, яка вас виснажує.',
    reversedEn: 'Stagnation, futile sacrifice, unwillingness to let go, a martyr complex. Perhaps it is time to exit a situation that is draining you.',
    advice: 'Відпустіть контроль і прийміть ситуацію. Пауза — це не поразка. Нове розуміння прийде тоді, коли ви перестанете чіплятися за старе.',
    adviceEn: 'Release control and accept the situation. A pause is not a defeat. New understanding will come when you stop clinging to the old.',
    loveAdvice: 'Дайте стосункам час дозріти. Не форсуйте події. Якщо стосунки зайшли в глухий кут — потрібна пауза для роздумів.',
    loveAdviceEn: 'Give your relationship time to ripen. Do not force events. If the relationship has reached a dead end — a pause for reflection is needed.',
    careerAdvice: 'Час переосмислити напрямок. Пауза в кар\'єрі може стати найкращою інвестицією. Те, що здається затримкою, насправді є підготовкою до стрибка.',
    careerAdviceEn: 'It is time to rethink your direction. A career pause may become the best investment. What seems like a delay is actually preparation for a leap.',
    financeAdvice: 'Зараз не час для активних фінансових дій. Заморозьте нові інвестиції та переосмисліть стратегію.',
    financeAdviceEn: 'Now is not the time for active financial moves. Freeze new investments and reconsider your strategy.',
    healthAdvice: 'Відпочинок та відновлення є абсолютно необхідними. Ваше тіло подає сигнал про потребу в паузі. Ретрит або відпустка зараз — ліки.',
    healthAdviceEn: 'Rest and recovery are absolutely essential. Your body is signaling a need for pause. A retreat or vacation right now is medicine.',
    spiritualAdvice: 'Це час для глибокої духовної трансформації через відпускання. Практикуйте медитацію капітуляції — здачі своєї волі вищій силі.',
    spiritualAdviceEn: 'This is a time for deep spiritual transformation through surrender. Practice the meditation of capitulation — yielding your will to a higher power.',
    yesNo: 'maybe', element: 'Вода', elementEn: 'Water', planet: 'Нептун', planetEn: 'Neptune',
  },
  {
    id: 13, name: 'Death', nameUk: 'Смерть', arcana: 'major',
    keywords: ['трансформація','завершення','оновлення','перехід'],
    keywordsEn: ['transformation','endings','renewal','transition'],
    description: 'Смерть рідко означає фізичну смерть. Це символ трансформації, завершення циклу та народження нового. Ця карта запрошує нас відпустити те, що відслужило свій час — звички, стосунки, ідеї — і відкритися для оновлення. Найкращий спосіб жити — не боятися змін.',
    descriptionEn: 'Death rarely signifies physical death. It is a symbol of transformation, the completion of a cycle, and the birth of the new. This card invites us to release what has served its time — habits, relationships, ideas — and open ourselves to renewal. The best way to live is to not fear change.',
    upright: 'Кінець одного циклу і початок нового. Трансформація неминуча та необхідна. Відпустіть те, що більше не служить вашому зростанню. Те, що здається втратою, є звільненням.',
    uprightEn: 'The end of one cycle and the beginning of another. Transformation is inevitable and necessary. Release what no longer serves your growth. What appears as loss is liberation.',
    reversed: 'Опір змінам, застрягання в минулому, страх трансформації. Ви не можете зупинити зміни — можете лише відкласти їх ціною власних страждань.',
    reversedEn: 'Resistance to change, being stuck in the past, fear of transformation. You cannot stop change — you can only postpone it at the cost of your own suffering.',
    advice: 'Не бійтеся завершень — вони відкривають нові можливості. Прийміть трансформацію з гідністю. Звільніть місце для нового.',
    adviceEn: 'Do not fear endings — they open new possibilities. Accept transformation with grace. Clear space for the new.',
    loveAdvice: 'Трансформація стосунків або їх природне завершення. Якщо стосунки руйнуються — це звільняє місце для кращого. Якщо продовжуються — вони трансформуються на новий рівень.',
    loveAdviceEn: 'A transformation of the relationship or its natural conclusion. If the relationship is crumbling — it frees space for something better. If it continues — it transforms to a new level.',
    careerAdvice: 'Час завершити старі проєкти та підготуватись до нових. Кар\'єрна трансформація — закриття одних дверей та відкриття інших.',
    careerAdviceEn: 'It is time to complete old projects and prepare for new ones. Career transformation — the closing of one door and the opening of another.',
    financeAdvice: 'Завершіть фінансові цикли: закрийте збиткові проєкти, відмовтесь від нерентабельних вкладень. Трансформація фінансової ситуації вимагає відпускання.',
    financeAdviceEn: 'Complete financial cycles: close unprofitable projects, abandon non-performing investments. Transformation of your financial situation requires letting go.',
    healthAdvice: 'Час для детоксикації — фізичної та емоційної. Відмовтесь від шкідливих звичок назавжди. Симптоми сигналізують про необхідність глибоких змін у способі життя.',
    healthAdviceEn: 'Time for detoxification — physical and emotional. Abandon harmful habits once and for all. Symptoms are signaling the need for deep lifestyle changes.',
    spiritualAdvice: 'Духовне відродження через смерть его. Практикуйте відпускання прив\'язаностей. Медитація на непостійність усього сущого — найглибша практика для вас зараз.',
    spiritualAdviceEn: 'Spiritual rebirth through the death of the ego. Practice releasing attachments. Meditation on the impermanence of all things is the most profound practice for you now.',
    yesNo: 'no', element: 'Вода', elementEn: 'Water', planet: 'Плутон', planetEn: 'Pluto',
  },
  {
    id: 14, name: 'Temperance', nameUk: 'Поміркованість', arcana: 'major',
    keywords: ['баланс','помірність','терпіння','гармонія'],
    keywordsEn: ['balance','temperance','patience','harmony'],
    description: 'Поміркованість — карта алхімії та досконалого балансу. Янгол переливає воду між двома чашами, і жодна крапля не проливається. Ця карта уособлює мистецтво знаходити золоту середину та про терпіння як найвищу форму мудрості.',
    descriptionEn: 'Temperance is the card of alchemy and perfect balance. An angel pours water between two cups without spilling a single drop. This card embodies the art of finding the golden mean and patience as the highest form of wisdom.',
    upright: 'Баланс і гармонія у всьому. Знайдіть золоту середину між крайнощами. Ваша помірність та терпіння творять зцілення. Час для інтеграції різних аспектів вашого життя.',
    uprightEn: 'Balance and harmony in all things. Find the golden mean between extremes. Your moderation and patience create healing. A time for integrating the different aspects of your life.',
    reversed: 'Дисбаланс, надмірність, нетерпіння, екстреми. Ви перегинаєте в одному напрямку. Відновіть рівновагу.',
    reversedEn: 'Imbalance, excess, impatience, extremes. You are bending too far in one direction. Restore your equilibrium.',
    advice: 'Знайдіть золоту середину. Не поспішайте — дозвольте процесу розгортатися у своєму темпі. Терпіння — ваша суперсила зараз.',
    adviceEn: 'Find the golden mean. Do not rush — allow the process to unfold at its own pace. Patience is your superpower right now.',
    loveAdvice: 'Гармонійні стосунки вимагають компромісу та взаємного терпіння. Уникайте крайнощів. Баланс між партнерами досягається через діалог та взаємоповагу.',
    loveAdviceEn: 'Harmonious relationships require compromise and mutual patience. Avoid extremes. Balance between partners is achieved through dialogue and mutual respect.',
    careerAdvice: 'Поміркований підхід до роботи принесе стабільний результат. Баланс між новими ідеями та перевіреними методами — ваш ключ до успіху.',
    careerAdviceEn: 'A measured approach to work will bring steady results. The balance between new ideas and proven methods is your key to success.',
    financeAdvice: 'Диверсифікація є ключем — не кладіть усі яйця в один кошик. Помірне витрачання та накопичення створюють стійку фінансову основу.',
    financeAdviceEn: 'Diversification is key — do not put all your eggs in one basket. Moderate spending and saving create a resilient financial foundation.',
    healthAdvice: 'Баланс — ключ до здоров\'я. Не перевантажуйтесь фізично чи емоційно. Практикуйте помірність у всьому.',
    healthAdviceEn: 'Balance is the key to health. Do not overload yourself physically or emotionally. Practice moderation in all things.',
    spiritualAdvice: 'Духовна алхімія — поєднання протилежностей у вищу єдність. Практикуйте інтеграцію: медитацію та активне служіння. Ваш янгол-охоронець особливо близько зараз.',
    spiritualAdviceEn: 'Spiritual alchemy is the merging of opposites into a higher unity. Practice integration: meditation and active service. Your guardian angel is especially close now.',
    yesNo: 'yes', element: 'Вогонь', elementEn: 'Fire', planet: 'Юпітер', planetEn: 'Jupiter',
  },
  {
    id: 15, name: 'The Devil', nameUk: 'Диявол', arcana: 'major',
    keywords: ['спокуса','залежність','матеріалізм','тінь'],
    keywordsEn: ['temptation','addiction','materialism','shadow'],
    description: 'Диявол говорить не про зовнішнє зло, а про наші власні обмежувальні переконання та залежності, які тримають нас у полоні. Два персонажі, прикуті до постаменту, тримаються за кайдани добровільно — вони могли б їх зняти. Ключ від кайданів у наших руках.',
    descriptionEn: 'The Devil speaks not of external evil, but of our own limiting beliefs and addictions that hold us captive. Two figures chained to a pedestal cling to their shackles voluntarily — they could remove them. The key to the chains lies in our own hands.',
    upright: 'Залежності та обмеження, які самі собі створили. Матеріалізм, зайва прив\'язаність. Побачте, що насправді тримає вас у полоні — і відпустіть.',
    uprightEn: 'Addictions and limitations you have created for yourself. Materialism, excessive attachment. See what truly holds you captive — and let it go.',
    reversed: 'Звільнення від залежності, пробудження, повернення сили. Ви починаєте бачити кайдани та звільняєтесь. Позитивні зміни можливі, коли ви визнаєте проблему.',
    reversedEn: 'Liberation from addiction, awakening, reclaiming your power. You are beginning to see the chains and freeing yourself. Positive change is possible once you acknowledge the problem.',
    advice: 'Усвідомте, що тримає вас у полоні. Залежності мають над вами лише стільки влади, скільки ви їм даєте. Ключ від ваших кайданів у ваших руках.',
    adviceEn: 'Recognize what holds you captive. Addictions have only as much power over you as you give them. The key to your chains is in your own hands.',
    loveAdvice: 'Можлива токсична динаміка у стосунках. Якщо ви відчуваєте себе в пастці — це тривожний знак. Поверніть собі власну силу.',
    loveAdviceEn: 'A toxic dynamic in the relationship is possible. If you feel trapped — this is a warning sign. Reclaim your own power.',
    careerAdvice: 'Не дозволяйте жадібності чи страху керувати рішеннями. Токсичне робоче середовище виснажує більше, ніж здається.',
    careerAdviceEn: 'Do not allow greed or fear to drive your decisions. A toxic work environment is more draining than it appears.',
    financeAdvice: 'Надмірні витрати, боргова залежність або азартні звички можуть бути проблемою. Час чесно поглянути на свої фінансові залежності.',
    financeAdviceEn: 'Excessive spending, debt dependency, or gambling habits may be the issue. It is time to honestly examine your financial addictions.',
    healthAdvice: 'Залежності — від речовин, їжі, телефону — негативно впливають на здоров\'я. Час для детоксикації та відновлення.',
    healthAdviceEn: 'Addictions — to substances, food, or screens — are negatively affecting your health. It is time for detoxification and recovery.',
    spiritualAdvice: 'Ця карта закликає до роботи з тінню. Ваші демони — це частини вас самих, що потребують любові та інтеграції. Пробудження починається з чесності.',
    spiritualAdviceEn: 'This card calls for shadow work. Your demons are parts of yourself that need love and integration. Awakening begins with honesty.',
    yesNo: 'no', element: 'Земля', elementEn: 'Earth', planet: 'Сатурн', planetEn: 'Saturn',
  },
  {
    id: 16, name: 'The Tower', nameUk: 'Вежа', arcana: 'major',
    keywords: ['руйнація','пробудження','хаос','одкровення'],
    keywordsEn: ['upheaval','awakening','chaos','revelation'],
    description: 'Вежа — карта раптових руйнувань, які відкривають правду. Блискавка вражає вежу, збудовану на хибних підставах. Але в цьому руйнуванні — звільнення. Краще зруйнована фальшива стабільність, ніж збережена ілюзія.',
    descriptionEn: 'The Tower is the card of sudden destruction that reveals the truth. Lightning strikes the tower built on false foundations. Yet within this destruction lies liberation. A shattered false stability is better than a preserved illusion.',
    upright: 'Раптові зміни та руйнація старих структур. Те, що здавалося непохитним, виявилось збудованим на піску. Хаос зараз — це очищення, що звільняє від ілюзій.',
    uprightEn: 'Sudden changes and the demolition of old structures. What seemed unshakable turns out to have been built on sand. The chaos now is a purification that frees you from illusions.',
    reversed: 'Уникнення катастрофи, менший струс, страх змін. Можливо, ви чіпляєтесь за руйновану структуру зі страху. Невеликий струс зараз запобіжить більшому пізніше.',
    reversedEn: 'Avoiding catastrophe, a lesser shock, fear of change. You may be clinging to a crumbling structure out of fear. A small tremor now will prevent a greater one later.',
    advice: 'Прийміть руйнацію старого як необхідний крок до кращого. Не чіпляйтесь за те, що вже почало розпадатися. Після бурі завжди приходить ясність.',
    adviceEn: 'Accept the destruction of the old as a necessary step toward something better. Do not cling to what has already begun to crumble. After every storm, clarity always arrives.',
    loveAdvice: 'Раптові зміни у стосунках. Конфлікт, якщо він чесний, може прояснити правду і зміцнити зв\'язок. Якщо стосунки руйнуються — можливо, вони були збудовані на хибному фундаменті.',
    loveAdviceEn: 'Sudden changes in a relationship. Honest conflict can reveal the truth and strengthen the bond. If the relationship is collapsing — perhaps it was built on a false foundation.',
    careerAdvice: 'Можливі несподівані зміни на роботі. Це не кінець — це звільнення для кращого. Будьте готові адаптуватись швидко.',
    careerAdviceEn: 'Unexpected changes at work are possible. This is not the end — it is liberation for something better. Be ready to adapt quickly.',
    financeAdvice: 'Фінансові потрясіння можливі. Перевірте стабільність своїх вкладень. Майте план Б.',
    financeAdviceEn: 'Financial upheaval is possible. Check the stability of your investments. Have a Plan B.',
    healthAdvice: 'Раптові зміни у стані здоров\'я можуть бути сигналом для серйозного перегляду способу життя. Не ігноруйте тривожні симптоми.',
    healthAdviceEn: 'Sudden changes in your health condition may be a signal for a serious lifestyle overhaul. Do not ignore alarming symptoms.',
    spiritualAdvice: 'Духовне пробудження через кризу — одне з найпотужніших. Прийміть "темну ніч душі" як подарунок трансформації.',
    spiritualAdviceEn: 'Spiritual awakening through crisis is among the most powerful. Embrace the "dark night of the soul" as a gift of transformation.',
    yesNo: 'no', element: 'Вогонь', elementEn: 'Fire', planet: 'Марс', planetEn: 'Mars',
  },
  {
    id: 17, name: 'The Star', nameUk: 'Зірка', arcana: 'major',
    keywords: ['надія','натхнення','зцілення','вірування'],
    keywordsEn: ['hope','inspiration','healing','faith'],
    description: 'Зірка — карта надії, відновлення та натхнення. Після бурі Вежі зірка освітлює шлях. Оголена постать переливає воду — символ очищення та зцілення. Зірка уособлює тиху впевненість, що все буде добре, навіть коли докази цього ще не видно.',
    descriptionEn: 'The Star is the card of hope, renewal, and inspiration. After the storm of The Tower, the Star illuminates the path. A bare figure pours water — a symbol of purification and healing. The Star embodies the quiet confidence that all will be well, even when the evidence is not yet visible.',
    upright: 'Надія та відновлення після труднощів. Ясне бачення майбутнього наповнює душу спокоєм. Ви отримуєте підтримку з вищих сфер. Ваша мрія досяжна — продовжуйте вірити.',
    uprightEn: 'Hope and renewal after hardship. A clear vision of the future fills the soul with peace. You are receiving support from higher realms. Your dream is attainable — keep believing.',
    reversed: 'Зневіра, втрата надії, розчарування. Ваша зірка тимчасово захована хмарами, але вона не зникла. Не здавайтесь — темрява передує світанку.',
    reversedEn: 'Despair, loss of hope, disillusionment. Your star is temporarily hidden behind clouds, but it has not vanished. Do not give up — darkness precedes the dawn.',
    advice: 'Вірте у кращий результат. Ваша надія — не ілюзія, вона є паливом для реальних змін. Відновіть зв\'язок із своїм вищим покликанням.',
    adviceEn: 'Believe in a better outcome. Your hope is not an illusion — it is the fuel for real change. Reconnect with your higher calling.',
    loveAdvice: 'Надія і зцілення у стосунках. Якщо є рани — вони гояться. Нові романтичні можливості несуть справжнє кохання. Відкрийте серце.',
    loveAdviceEn: 'Hope and healing in relationships. If there are wounds — they are mending. New romantic possibilities carry true love. Open your heart.',
    careerAdvice: 'Надихаючий час для мрій та планування. Ваше покликання виходить на перший план. Творчі проєкти, що надихають інших — ваш шлях зараз.',
    careerAdviceEn: 'An inspiring time for dreaming and planning. Your calling is coming to the forefront. Creative projects that inspire others are your path now.',
    financeAdvice: 'Після важкого фінансового періоду починається відновлення. Нові можливості для зростання добробуту приходять.',
    financeAdviceEn: 'After a difficult financial period, recovery is beginning. New opportunities for growing prosperity are arriving.',
    healthAdvice: 'Зцілення відбувається. Ваше тіло та душа відновлюються. Практикуйте холістичні методи зцілення. Надія є найкращим ліком.',
    healthAdviceEn: 'Healing is taking place. Your body and soul are recovering. Practice holistic healing methods. Hope is the best medicine.',
    spiritualAdvice: 'Ваш зв\'язок із вищою силою та ангелами-охоронцями особливо сильний зараз. Астрологія та зоряна магія відповідають вашому духовному рівню.',
    spiritualAdviceEn: 'Your connection with higher power and guardian angels is especially strong now. Astrology and stellar magic correspond to your spiritual level.',
    yesNo: 'yes', element: 'Повітря', elementEn: 'Air', planet: 'Уран', planetEn: 'Uranus',
  },
  {
    id: 18, name: 'The Moon', nameUk: 'Місяць', arcana: 'major',
    keywords: ['ілюзії','підсвідомість','страхи','невизначеність'],
    keywordsEn: ['illusions','subconscious','fears','uncertainty'],
    description: 'Місяць — карта ілюзій, підсвідомих страхів та того, що ховається у тіні. Місяць не має власного світла — він лише відбиває сонячне. Ця карта говорить про плутанину та невизначеність, коли не можемо відрізнити реальне від уявного. Місяць запрошує зануритись у власні глибини.',
    descriptionEn: 'The Moon is the card of illusions, subconscious fears, and that which hides in the shadows. The Moon has no light of its own — it merely reflects the Sun. This card speaks of confusion and uncertainty, when we cannot distinguish the real from the imagined. The Moon invites us to dive into our own depths.',
    upright: 'Ілюзії та страхи туманять розум. Ситуація не є такою, якою здається. Довіряйте відчуттям, але перевіряйте факти. Підсвідомість надсилає важливі повідомлення через сни та інтуїцію.',
    uprightEn: 'Illusions and fears cloud the mind. The situation is not what it appears to be. Trust your feelings, but verify the facts. The subconscious is sending important messages through dreams and intuition.',
    reversed: 'Ясність після заплутаності, подолання страхів, вихід з ілюзій. Туман розсіюється — правда стає видимою.',
    reversedEn: 'Clarity after confusion, overcoming fears, emerging from illusions. The fog is lifting — the truth becomes visible.',
    advice: 'Не довіряйте першому враженню. Зупиніться та перевірте факти. Зверніть увагу на сни — вони несуть важливі послання.',
    adviceEn: 'Do not trust first impressions. Pause and verify the facts. Pay attention to your dreams — they carry important messages.',
    loveAdvice: 'Можливі непорозуміння та приховані почуття. Ревнощі та підозри можуть бути необґрунтованими. Спілкуйтесь відкрито.',
    loveAdviceEn: 'Misunderstandings and hidden feelings are possible. Jealousy and suspicions may be unfounded. Communicate openly.',
    careerAdvice: 'Не приймайте важливих рішень у туманній ситуації. Щось може бути приховано від вас. Зачекайте на повну інформацію.',
    careerAdviceEn: 'Do not make important decisions in a foggy situation. Something may be hidden from you. Wait for full information.',
    financeAdvice: 'Обережно з фінансовими схемами та обіцянками. Не ухвалюйте фінансових рішень, керуючись страхом. Чекайте ясності.',
    financeAdviceEn: 'Be cautious with financial schemes and promises. Do not make financial decisions driven by fear. Wait for clarity.',
    healthAdvice: 'Тривожні розлади, проблеми зі сном, гормональні порушення — можлива тема зараз. Практикуйте медитацію та роботу з тінню.',
    healthAdviceEn: 'Anxiety disorders, sleep problems, hormonal imbalances — these may be relevant themes now. Practice meditation and shadow work.',
    spiritualAdvice: 'Глибока робота зі сновидіннями та підсвідомістю. Ведіть щоденник снів. Місячна магія та ритуали за фазами Місяця — ваші духовні інструменти.',
    spiritualAdviceEn: 'Deep work with dreams and the subconscious. Keep a dream journal. Lunar magic and rituals aligned with the Moon phases are your spiritual instruments.',
    yesNo: 'maybe', element: 'Вода', elementEn: 'Water', planet: 'Нептун', planetEn: 'Neptune',
  },
  {
    id: 19, name: 'The Sun', nameUk: 'Сонце', arcana: 'major',
    keywords: ['радість','успіх','оптимізм','сяйво'],
    keywordsEn: ['joy','success','optimism','radiance'],
    description: 'Сонце — одна з найпозитивніших карт Таро. Яскравий сонячний диск освітлює все навкруги, а радісна дитина на білому коні символізує чисту радість та вітальність. Сонце нагадує: ваш природний стан — це радість і достаток.',
    descriptionEn: 'The Sun is one of the most positive cards in the Tarot. A bright solar disk illuminates everything around, and a joyful child on a white horse symbolizes pure joy and vitality. The Sun reminds us: your natural state is joy and abundance.',
    upright: 'Яскравий успіх, радість та вітальність. Все стає ясним та можливим. Ваша енергія на піку, успіх очевидний для всіх навкруги. Святкуйте — ви заслуговуєте на це!',
    uprightEn: 'Brilliant success, joy, and vitality. Everything becomes clear and possible. Your energy is at its peak, success is evident to all around you. Celebrate — you deserve it!',
    reversed: 'Тимчасові труднощі, прихована радість, самовпевненість. Сонце зайшло за хмари тимчасово. Дозвольте собі бути щасливим.',
    reversedEn: 'Temporary difficulties, hidden joy, overconfidence. The Sun has gone behind the clouds temporarily. Allow yourself to be happy.',
    advice: 'Сяйте своїм світлом! Ваша радість та оптимізм — подарунок для оточуючих. Діліться щастям — воно від цього лише збільшується.',
    adviceEn: 'Shine your light! Your joy and optimism are a gift to those around you. Share happiness — it only grows when shared.',
    loveAdvice: 'Яскраве, радісне кохання. Стосунки наповнені теплом та радістю. Для одиноких — час для щасливих зустрічей.',
    loveAdviceEn: 'Bright, joyous love. Relationships are filled with warmth and delight. For the unattached — a time for happy encounters.',
    careerAdvice: 'Успіх та визнання! Ваші таланти помічені та оцінені. Час для підвищення або нових можливостей.',
    careerAdviceEn: 'Success and recognition! Your talents have been noticed and valued. A time for promotion or new opportunities.',
    financeAdvice: 'Фінансове процвітання та достаток. Інвестиції дають щедрі плоди. Діліться добробутом — він від цього лише зростає.',
    financeAdviceEn: 'Financial prosperity and abundance. Investments are yielding generous returns. Share your wealth — it only grows from sharing.',
    healthAdvice: 'Ваше здоров\'я та вітальність на чудовому рівні. Проводьте більше часу на сонці та свіжому повітрі. Радість та сміх — найкраща медицина.',
    healthAdviceEn: 'Your health and vitality are at a wonderful level. Spend more time in the sun and fresh air. Joy and laughter are the best medicine.',
    spiritualAdvice: 'Ваше вище "Я" сяє крізь вас. Практикуйте серцеву медитацію та роботу із сонячною чакрою. Несіть світло іншим.',
    spiritualAdviceEn: 'Your Higher Self shines through you. Practice heart meditation and work with the solar plexus chakra. Carry the light to others.',
    yesNo: 'yes', element: 'Вогонь', elementEn: 'Fire', planet: 'Сонце', planetEn: 'Sun',
  },
  {
    id: 20, name: 'Judgement', nameUk: 'Суд', arcana: 'major',
    keywords: ['відродження','призначення','пробудження','вирок'],
    keywordsEn: ['rebirth','calling','awakening','judgment'],
    description: 'Суд — карта вищого покликання та духовного пробудження. Янгол сурмить у трубу, і мертві піднімаються з труни — символ воскресіння та відповіді на вищий поклик. Ця карта говорить про той момент, коли ми чуємо голос своєї душі настільки чітко, що не можемо більше ігнорувати.',
    descriptionEn: 'Judgement is the card of higher calling and spiritual awakening. An angel sounds the trumpet, and the dead rise from their coffins — a symbol of resurrection and answering the divine call. This card speaks of that moment when we hear the voice of our soul so clearly that we can no longer ignore it.',
    upright: 'Вище покликання та духовне пробудження. Час для фундаментального переосмислення свого шляху. Ваше справжнє призначення кличе вас. Оцініть пройдений шлях та рушайте далі оновленими.',
    uprightEn: 'A higher calling and spiritual awakening. A time for a fundamental reassessment of your path. Your true purpose is calling you. Evaluate the journey so far and move forward renewed.',
    reversed: 'Самоосуд, ігнорування покликання, страх змін. Ви тягнете вантаж провини або відмовляєтесь чути голос своєї душі. Пробачте собі та рушайте далі.',
    reversedEn: 'Self-judgment, ignoring your calling, fear of change. You are carrying the weight of guilt or refusing to hear the voice of your soul. Forgive yourself and move forward.',
    advice: 'Прислухайтесь до вищого покликання. Яка ваша справжня місія? Пробачте собі минуле та почніть з чистого аркуша.',
    adviceEn: 'Listen to your higher calling. What is your true mission? Forgive yourself for the past and begin with a clean slate.',
    loveAdvice: 'Важливе рішення щодо стосунків. Або відродження любові на новому рівні, або чесне завершення. Прислухайтеся до глибинного відчуття правди.',
    loveAdviceEn: 'An important decision regarding your relationship. Either a rebirth of love on a new level, or an honest ending. Listen to the deep feeling of truth within you.',
    careerAdvice: 'Значна зміна кар\'єри або рівня відповідальності. Ваше покликання стає очевидним. Не бійтесь відповісти на нього.',
    careerAdviceEn: 'A significant career change or shift in level of responsibility. Your calling is becoming clear. Do not be afraid to answer it.',
    financeAdvice: 'Фінансова переоцінка та нова стратегія. Ваша справжня місія може бути пов\'язана з певним способом заробітку.',
    financeAdviceEn: 'A financial reassessment and new strategy. Your true mission may be connected to a particular way of earning.',
    healthAdvice: 'Пробудження до здорового способу життя. Тіло готове до трансформації. Слухайте своє тіло уважно.',
    healthAdviceEn: 'An awakening to a healthy lifestyle. Your body is ready for transformation. Listen to your body attentively.',
    spiritualAdvice: 'Духовне пробудження — це і є головне послання цієї карти. Ваша душа готова до наступного рівня усвідомленості. Відповідайте на поклик.',
    spiritualAdviceEn: 'Spiritual awakening is the central message of this card. Your soul is ready for the next level of awareness. Answer the call.',
    yesNo: 'yes', element: 'Вогонь', elementEn: 'Fire', planet: 'Плутон', planetEn: 'Pluto',
  },
  {
    id: 21, name: 'The World', nameUk: 'Світ', arcana: 'major',
    keywords: ['завершення','цілісність','досягнення','інтеграція'],
    keywordsEn: ['completion','wholeness','achievement','integration'],
    description: 'Світ — останній Аркан Великого циклу, карта тріумфу та цілісності. Фігура у центрі кола — символ завершеності та гармонії з усім Всесвітом. Ця карта говорить про ту мить, коли ми відчуваємо себе повністю реалізованими та єдиними зі Всесвітом.',
    descriptionEn: 'The World is the final Arcanum of the Great cycle, the card of triumph and wholeness. A figure at the center of a circle symbolizes completeness and harmony with the entire Universe. This card speaks of that moment when we feel fully realized and one with the Universe.',
    upright: 'Завершення великого циклу, повне досягнення мети. Ви стоїте на вершині. Визнання, успіх та відчуття цілісності. Святкуйте — і готуйтеся до нового, ще більшого циклу.',
    uprightEn: 'The completion of a great cycle, full achievement of the goal. You stand at the summit. Recognition, success, and a feeling of wholeness. Celebrate — and prepare for a new, even greater cycle.',
    reversed: 'Незавершені справи, відкладені успіхи, страх завершення. Фінальний крок лишається незробленим. Що заважає вам вийти на фінішну пряму?',
    reversedEn: 'Unfinished business, delayed success, fear of completion. The final step remains untaken. What is preventing you from crossing the finish line?',
    advice: 'Відсвяткуйте свої досягнення! Завершіть усе, що почали. Новий цикл вже чекає — спочатку закрийте поточний з гідністю та подякою.',
    adviceEn: 'Celebrate your achievements! Complete everything you have started. A new cycle is already waiting — first close the current one with grace and gratitude.',
    loveAdvice: 'Стосунки досягли рівня глибокого союзу та цілісності. Можлива весілля або офіційне оформлення стосунків. Двоє стали одним цілим.',
    loveAdviceEn: 'The relationship has reached a level of deep union and wholeness. Marriage or an official commitment is possible. Two have become one.',
    careerAdvice: 'Видатний успіх та визнання у кар\'єрі. Ваша мета досягнута. Зупиніться, щоб відзначити перемогу, а потім плануйте наступний великий крок.',
    careerAdviceEn: 'Outstanding success and recognition in your career. Your goal has been achieved. Pause to honor your victory, then plan your next great step.',
    financeAdvice: 'Фінансова мета досягнута або близька до досягнення. Час пожинати плоди своїх зусиль та забезпечити стабільну основу.',
    financeAdviceEn: 'Your financial goal has been achieved or is close to being reached. It is time to reap the fruits of your efforts and secure a stable foundation.',
    healthAdvice: 'Відмінне здоров\'я та вітальність. Ваше тіло та душа в гармонії. Відсвяткуйте своє здоров\'я та підтримуйте його.',
    healthAdviceEn: 'Excellent health and vitality. Your body and soul are in harmony. Celebrate your health and maintain it.',
    spiritualAdvice: 'Духовне завершення великого циклу. Ви інтегрували всі уроки. Новий спіральний рівень вашого духовного розвитку відкривається. Час навчати інших.',
    spiritualAdviceEn: 'The spiritual completion of a great cycle. You have integrated all the lessons. A new spiral level of your spiritual development is opening. It is time to teach others.',
    yesNo: 'yes', element: 'Земля', elementEn: 'Earth', planet: 'Сатурн', planetEn: 'Saturn',
  },
  ...MINOR_ARCANA,
];

export const FALLBACK_MEDITATIONS: MeditationItem[] = [
  { id: '1', title: 'Ранкова Активація',  subtitle: 'Налаштуйте себе на продуктивний день', guide: 'Майстер Еліра',    duration: '10 хв', durationSec: 600,  moods: ['joy','energy'],       goals: ['energy','focus'],         frequency: '528 Гц',  description: 'Пробудіть свою внутрішню силу.', artwork: { gradient: ['#78350F','#D97706','#FDE68A'], emoji: '☀️', accentColor: '#FCD34D' }, isPremium: false },
  { id: '2', title: 'Зцілення Серця',     subtitle: 'Відкрийте серцевий центр',             guide: 'Майстер Еліра',    duration: '15 хв', durationSec: 900,  moods: ['sadness','anxiety'],  goals: ['healing','spiritual'],    frequency: '639 Гц',  description: 'Медитація для Анахата чакри.',   artwork: { gradient: ['#064E3B','#059669','#A7F3D0'], emoji: '💚', accentColor: '#34D399' }, isPremium: true  },
  { id: '3', title: 'Глибокий Сон',       subtitle: 'Підготовка до відновного сну',          guide: 'Голос Місяця',     duration: '20 хв', durationSec: 1200, moods: ['fatigue','stress'],   goals: ['sleep'],                  frequency: '432 Гц',  description: 'Розслабте тіло та розум.',       artwork: { gradient: ['#1E1B4B','#4338CA','#A5B4FC'], emoji: '🌙', accentColor: '#818CF8' }, isPremium: true  },
  { id: '4', title: 'Маніфестація Мрій',  subtitle: 'Притягніть бажане у своє життя',       guide: 'Провідник Зірок',  duration: '12 хв', durationSec: 720,  moods: ['joy','energy'],       goals: ['confidence','spiritual'], frequency: '963 Гц',  description: 'Медитація для маніфестації.',    artwork: { gradient: ['#3B0764','#7C3AED','#DDD6FE'], emoji: '✨', accentColor: '#A78BFA' }, isPremium: true  },
  { id: '5', title: 'Захист Аури',        subtitle: 'Очищення та захист енергетичного поля', guide: 'Стражник Світла',  duration: '8 хв',  durationSec: 480,  moods: ['anxiety','stress'],   goals: ['healing','confidence'],   frequency: '741 Гц',  description: 'Очистіть ауру від чужих енергій.', artwork: { gradient: ['#1E3A5F','#2563EB','#BFDBFE'], emoji: '🛡️', accentColor: '#60A5FA' }, isPremium: false },
  { id: '6', title: 'Заземлення',         subtitle: 'Стабілізація кореневої чакри',          guide: 'Дух Землі',        duration: '10 хв', durationSec: 600,  moods: ['anxiety','fatigue'],  goals: ['energy','confidence'],    frequency: '396 Гц',  description: 'Зміцніть Муладхара чакру.',      artwork: { gradient: ['#14532D','#15803D','#BBF7D0'], emoji: '🌱', accentColor: '#4ADE80' }, isPremium: false },
  { id: '7', title: 'Вдячність',          subtitle: 'Практика вдячності для серця',          guide: 'Майстер Еліра',    duration: '7 хв',  durationSec: 420,  moods: ['sadness','joy'],      goals: ['healing','spiritual'],    frequency: '528 Гц',  description: 'Наповніться вдячністю.',         artwork: { gradient: ['#831843','#BE185D','#FBCFE8'], emoji: '🙏', accentColor: '#F472B6' }, isPremium: false },
  { id: '8', title: 'Ясність Розуму',     subtitle: 'Концентрація та фокус думок',           guide: 'Мудрець Долі',     duration: '5 хв',  durationSec: 300,  moods: ['stress','fatigue'],   goals: ['focus','energy'],         frequency: '285 Гц',  description: 'Знайдіть кристальну ясність.',   artwork: { gradient: ['#0C4A6E','#0284C7','#BAE6FD'], emoji: '🔮', accentColor: '#38BDF8' }, isPremium: false },
];

export const FALLBACK_MOODS: MoodOption[] = [
  { id: 'anxiety', label: 'Тривога', emoji: '😰', color: '#6366F1' },
  { id: 'stress',  label: 'Стрес',   emoji: '😤', color: '#EF4444' },
  { id: 'sadness', label: 'Смуток',  emoji: '😢', color: '#38BDF8' },
  { id: 'fatigue', label: 'Втома',   emoji: '😴', color: '#64748B' },
  { id: 'joy',     label: 'Радість', emoji: '😊', color: '#F59E0B' },
  { id: 'anger',   label: 'Злість',  emoji: '😠', color: '#F97316' },
];

export const FALLBACK_GOALS: GoalOption[] = [
  { id: 'sleep',      label: 'Сон',         emoji: '🌙', color: '#818CF8' },
  { id: 'focus',      label: 'Фокус',       emoji: '🎯', color: '#34D399' },
  { id: 'energy',     label: 'Енергія',     emoji: '⚡', color: '#FBBF24' },
  { id: 'confidence', label: 'Впевненість', emoji: '💪', color: '#F472B6' },
  { id: 'spiritual',  label: 'Духовне',     emoji: '✨', color: '#A78BFA' },
  { id: 'healing',    label: 'Зцілення',    emoji: '💚', color: '#4ADE80' },
];
