import React from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { Colors, Spacing, FontSize, BorderRadius } from '@/constants/theme';
import { useAppStore } from '@/stores/useAppStore';
import { useI18n } from '@/lib/i18n';

export default function AIDisclosureScreen() {
  const router = useRouter();
  const { next } = useLocalSearchParams<{ next?: string }>();
  const setAiConsentGiven = useAppStore((s) => s.setAiConsentGiven);
  const { locale } = useI18n();

  const isUk = locale === 'uk';

  const handleAccept = () => {
    setAiConsentGiven();
    const target = next ?? '/ai/chat';
    router.replace(target as any);
  };

  const handleDecline = () => {
    router.back();
  };

  return (
    <View style={styles.container}>
      <LinearGradient colors={['#0F0820', '#1E1B4B']} style={styles.header}>
        <View style={styles.iconWrap}>
          <LinearGradient colors={['#4338CA', '#7C3AED']} style={styles.iconGrad}>
            <Ionicons name="sparkles" size={32} color="#fff" />
          </LinearGradient>
        </View>
        <Text style={styles.title}>
          {isUk ? 'AI Помічник' : 'AI Assistant'}
        </Text>
        <Text style={styles.subtitle}>
          {isUk ? 'Перед початком, будь ласка, прочитайте' : 'Before starting, please read'}
        </Text>
      </LinearGradient>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="hardware-chip-outline" size={20} color={Colors.primary} />
            <Text style={styles.sectionTitle}>
              {isUk ? 'Що таке AI в цьому додатку' : 'What is AI in this app'}
            </Text>
          </View>
          <Text style={styles.body}>
            {isUk
              ? 'Відповіді генеруються штучним інтелектом (Claude від Anthropic). AI аналізує надані вами дані та формулює інтерпретації в езотеричному контексті.'
              : 'Responses are generated by artificial intelligence (Claude by Anthropic). AI analyzes the data you provide and formulates interpretations in an esoteric context.'}
          </Text>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="information-circle-outline" size={20} color={Colors.accent} />
            <Text style={styles.sectionTitle}>
              {isUk ? 'Розважальний характер' : 'Entertainment purpose'}
            </Text>
          </View>
          <Text style={styles.body}>
            {isUk
              ? 'Усі відповіді AI мають виключно розважальний характер. Вони не є медичними, юридичними, психологічними або фінансовими порадами.'
              : 'All AI responses are for entertainment purposes only. They are not medical, legal, psychological, or financial advice.'}
          </Text>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="shield-outline" size={20} color="#22c55e" />
            <Text style={styles.sectionTitle}>
              {isUk ? 'Ваші дані' : 'Your data'}
            </Text>
          </View>
          <Text style={styles.body}>
            {isUk
              ? 'Ваше ім\'я та дата народження можуть передаватись AI для персоналізованих відповідей. Anthropic обробляє запити відповідно до своєї Політики конфіденційності.'
              : "Your name and date of birth may be sent to the AI for personalized responses. Anthropic processes requests according to their Privacy Policy."}
          </Text>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="warning-outline" size={20} color="#f97316" />
            <Text style={styles.sectionTitle}>
              {isUk ? 'Обмеження' : 'Limitations'}
            </Text>
          </View>
          <Text style={styles.body}>
            {isUk
              ? 'AI може помилятись. Не приймайте важливих рішень виключно на основі відповідей AI. За потреби звертайтесь до кваліфікованих фахівців.'
              : 'AI can make mistakes. Do not make important decisions based solely on AI responses. Consult qualified professionals when needed.'}
          </Text>
        </View>

        <TouchableOpacity onPress={handleAccept} activeOpacity={0.85} style={{ marginTop: Spacing.xl }}>
          <LinearGradient
            colors={[Colors.primary, '#6D28D9']}
            style={styles.acceptBtn}
            start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
          >
            <Ionicons name="checkmark-circle-outline" size={20} color="#fff" />
            <Text style={styles.acceptText}>
              {isUk ? 'Зрозумів, продовжити' : 'I understand, continue'}
            </Text>
          </LinearGradient>
        </TouchableOpacity>

        <TouchableOpacity onPress={handleDecline} activeOpacity={0.7} style={styles.declineBtn}>
          <Text style={styles.declineText}>
            {isUk ? 'Назад' : 'Go back'}
          </Text>
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: {
    paddingTop: 70, paddingBottom: Spacing.xl, paddingHorizontal: Spacing.lg,
    alignItems: 'center', gap: Spacing.sm,
  },
  iconWrap: { marginBottom: 4 },
  iconGrad: {
    width: 68, height: 68, borderRadius: 34,
    alignItems: 'center', justifyContent: 'center',
  },
  title: { color: Colors.text, fontSize: FontSize.xxl, fontWeight: '800', textAlign: 'center' },
  subtitle: { color: 'rgba(167,139,250,0.7)', fontSize: FontSize.sm, textAlign: 'center' },

  content: { padding: Spacing.lg },

  section: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: BorderRadius.lg,
    borderWidth: 1, borderColor: Colors.border,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
  },
  sectionHeader: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  sectionTitle: { color: Colors.text, fontSize: FontSize.md, fontWeight: '700', flex: 1 },
  body: { color: Colors.textSecondary, fontSize: FontSize.sm, lineHeight: 22 },

  acceptBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 8, borderRadius: BorderRadius.lg, paddingVertical: 16,
  },
  acceptText: { color: '#fff', fontSize: FontSize.md, fontWeight: '700' },

  declineBtn: {
    alignItems: 'center', paddingVertical: Spacing.lg,
  },
  declineText: { color: Colors.textMuted, fontSize: FontSize.md },
});
